### ISSUE TITLE
Broken in 3.8 with Debug set to True (PHP 5.4.x-5.5.x)

### ISSUE THREAD

**Issue by christopheranderton** [bonfirelab/bearded#1]
Posted this at the WordPress Support Forum (http://wordpress.org/support/topic/broken-in-38-39) also.

When activating the theme it fails (not gracefully) with debug warnings and also (may be a WP 3.8 bug) breaks accented characters like ÅÄÖ in both the admin and in the front when debug=true is set. With set to false it works (with the warnings muted in browser).

With  **PHP 5.3.27, the debug messages are gone.** . So it's a PHP issue.  However, most hosts i use, is running PHP 5.4.x and some of them moving to 5.5.x. (in Sweden at least). 
- **WP/PHP Debug Output:** http://pastebin.com/TJ8a1zGw
- **Screenshots:** http://cl.ly/T15b and http://cl.ly/T0TC (CloudApp Links)
### Test Enviroment 1:
- **Server:** MAMP (Apache 2.2.25, PHP 5.5.3, MySQL 5.5.33)
- **Install:** WordPress 3.8 (Release) - WooCommerce Testing
- **WP Debug:** True / False
- **WooCommerce Debug:** False
- **WP Language:** Tested with Swedish and English (standard)
- **Plugins active:** 
  Justin Tadlock Plugins (Custom Background Extended, Custom Content Portfolio, Custom Header Extended, Get The Image, Whistles), Developer, Log Deprecated Notices, Theme Check, Regenerate Thumbnails, Simply Show IDs, Theme Mentor, User Switching, WordPress Importer, WooCommerce)
### Test Enviroment 2:
- **Server:** MAMP (Apache 2.2.25, **_PHP 5.4.19_**, MySQL 5.5.33)
- **Install:** WordPress 3.8 (Release) - Standard testing
- **WP Debug:** True / False
- **WP Language** English (standard)
- **Plugins active (on/off):** 
  Developer, Log Deprecated Notices, Theme Check, WordPress Importer

**Comment by christopheranderton** [comment]
A workaround is to set `error_reporting( E_ALL ^ E_STRICT );` instead of `define( "WP_DEBUG", true );` to supress  messages and still have the normal WP debug behaviour.

**Comment by nackle2k10** [comment]
https://github.com/bonfirelab/bearded/commit/59fc2f523d46e6c3480c268a07c21da658ba8cc0 Fixed on v1.0.0, I've moved all to the version 1.0.0 since there are major change including woocommerce integration. I created most change locally wihtout any commit and will start whole new commit starting from 1.0.0
