### ISSUE TITLE
Sidebar missing since the last update

### ISSUE THREAD

**Issue by pydubreucq** [bonfirelab/bearded#11]
Hi,
I've made the last update, and I've one problem and one suggest
- The sidebar disappeared, I'm using layout "Two Columns, Left"

You can see my problem on my website :
http://blog.admin-linux.org/
For the sidebar :
http://blog.admin-linux.org/administration/shell-historiser-logguer-toutes-les-commandes-shell
Thanks by advance
Bye

**Comment by nackle2k10** [comment]
Fixed https://github.com/bonfirelab/bearded/commit/854c9a305b46fe76f4a6324cc98a76cd0b55ae85 , thanks for reporting
