### ISSUE TITLE
Icon class icons not working...

### ISSUE THREAD

**Issue by iDare87** [bonfirelab/bearded#17]
Hi there - I have tried numerous times to get the chosen icons to show and it won't work...bit of a pain as it's for the Services widget so looks quite silly without them there!

See the images attached and let me know how to solve please. Thanks for this otherwise brilliant template too.

![image](https://cloud.githubusercontent.com/assets/7880081/3269661/4feede36-f2f2-11e3-919e-5c0f90b42c06.png)

![image](https://cloud.githubusercontent.com/assets/7880081/3269668/6f811534-f2f2-11e3-9a50-61c752c00531.png)

**Comment by nackle2k10** [comment]
This theme still using Font Awesome v3, I've been stated in the documentation, so icon class prefix is icon- not fa-
