### ISSUE TITLE
"Add to cart" button missing

### ISSUE THREAD

**Issue by kinkuroai** [bonfirelab/bearded#22]
Looking at the theme demo of bearded, there seems to be an "Add to cart" button on the products listed on the front page. Unfortunately, on my end, only the "Add to wishlist" is visible. How do I enable the "Add to cart" button?

**Comment by nackle2k10** [comment]
Are you using woocommerce v2.2? The theme still not compatible with wc2.2

**Comment by kinkuroai** [comment]
Yes. So the only workaround to this is by downgrading? If so, to what version? 2.0.x, 2.1.x?

**Comment by nackle2k10** [comment]
Yes, the only solution right now is to downgrade the wc plugin. But i have
a plan for upgrading the compatibility
