### ISSUE TITLE
Feature : Image Dimension

### ISSUE THREAD

**Issue by pydubreucq** [bonfirelab/bearded#3]
Hi,
I'm sorry, I'm French and I don't speak english very well
Is it possible to add the image dimension on the <img> html because, it's really bad for web performance to don't show there.
I don't have dimension on the logo Image, the client list.
Best Regards
Pierre-Yves

**Comment by nackle2k10** [comment]
the only way is to modify the source for the widget. since it's an input text field, you'll need a extra functions to detect the image dimension and put it in the html tag
